### ISSUE TITLE
markdown's blank lines are deleted by latex_envs

### ISSUE THREAD

**Issue by shanhaiying** [jfbercher/jupyter_latex_envs#1]
`\begin{proof}
$$\alpha$$ bb

cc

dd

\end{proof}

$$\alpha$$ bb

cc

dd`

Before enabling latex_envs:

![image](https://cloud.githubusercontent.com/assets/1595652/18191629/2fc966e8-70ff-11e6-80e7-dd91fe4553aa.png)

After enabling latex_envs:

![image](https://cloud.githubusercontent.com/assets/1595652/18191646/527f2060-70ff-11e6-9aff-d93510f39cf5.png)

**Comment by jfbercher** [comment]
@shanhaiying This was unfortunately introduced in the previous round. I think it is fixed. 
Also added support for comments % (in envs) and linebreaks \\
Thanks for the inputs.
