### ISSUE TITLE
Is there an easy way to adding tex macros to mathjax by latex_envs?

### ISSUE THREAD

**Issue by shanhaiying** [jfbercher/jupyter_latex_envs#4]
I want to use some latex macros while typesetting materials in jupyter notebook. 
For example:
\newcommand{\C}{\mathbb{C}}
\newcommand{\R}{\mathbb{R}}
\newcommand{\Z}{\mathbb{Z}}
\newcommand{\N}{\mathbb{N}}
\newcommand{\D}{\mathscr{D}}
\newcommand{\F}{\mathscr{F}}

I  once  did it by adding the following code to jupyter's costum.js file:

MathJax.Hub.Config({
    TeX: {
    Macros: {
        vect: ["{\vec #1}",1],
        abs: ["{\lvert #1 \rvert}",1],
        floor: ["{\left\lfloor #1 \right\rfloor}",1],
        ceil: ["{\left\lceil #1 \right\rceil}",1],
......

But now it do not work for me.  I have tried to use javascript in notebook's code cell to enable these macros. unfortunately, the magic method %%javascript, %%html can not work for unknown reasons.

![image](https://cloud.githubusercontent.com/assets/1595652/18257038/11dc6c72-73f0-11e6-8295-af576438f838.png)

@jfbercher , can you give me some proposal to solve difficult problems? Thanks!

**Comment by jfbercher** [comment]
This is an excerpt of what I use (with Python) :  

```
from IPython.display import clear_output, display, HTML, Image, Javascript
print("... Some LaTeX definitions")

LaTeXdefs=r"""
$$\def\egalpardef{\mathop{=}\limits^\triangle}
\def\xb{\mathbf{x}}
\def\RR{\mathbb{R}} 
\def\CC{\mathbb{C}} 
\def\mystar{{*}}
\def\deriv#1#2{\frac{\mathrm{d}#1}{\mathrm{d}#2}}
\def\Lambdab{\mathbf{\Lambda}}
\def\Ab{\mathbf{A}}
\def\sinc#1{\mathrm{sinc\left(#1\right)}}
\newcommand{\C}{\mathbb{C}}
\newcommand{\R}{\mathbb{R}}
\newcommand{\Z}{\mathbb{Z}}
\newcommand{\N}{\mathbb{N}}
\newcommand{\D}{\mathscr{D}}
\newcommand{\F}{\mathscr{F}}
$$
"""
display(HTML(LaTeXdefs))
```

![image](https://cloud.githubusercontent.com/assets/7596356/18257421/a8479a24-73c3-11e6-937a-97d3079573ad.png)
which gives
![image](https://cloud.githubusercontent.com/assets/7596356/18257429/c78d22dc-73c3-11e6-8bf3-efb23ff7c93a.png)
Best!

**Comment by jfbercher** [comment]
I put all these in an init file, eg `nbinit.ipy`, and at the top of my notebook, I use the magic

```
%run nbinit.ipy
```

or you can even put that in your ipython startup file `~/.ipython/profile_default/startup/00-startup.py`

**Comment by shanhaiying** [comment]
Thanks for your kind response. There are some bug in my jupyter notebook of sagemath. The method can not work for me because Javascript or HTML function can not work normally. 
![image](https://cloud.githubusercontent.com/assets/1595652/18258904/682a75c2-7410-11e6-99da-578173a8ef32.png)

**Comment by shanhaiying** [comment]
I have found the reason which cause the method HTML and Javascript not to work properly.
The sagemath command "pretty_print_default(True);" causes the problem.
BTW,  the commands having output such as HTML can not be executed properly in  Jupyter's startup file.

**Comment by jfbercher** [comment]
So it is solved?

**Comment by shanhaiying** [comment]
I delete the call of pretty_print_default and display the definitions of tex commands  as you do in the head of every notebook. The macros work normally now.  The only inconvenience is that the code of display have to be added manually. It is  beautiful thing if latex_envs can support some method of loading the definitions of tex commands.

   About the enumerate of sections,  I store the initial  values of counters such as chapters sections and subsections in notebook's metadata and copy these values during  the notebook loaded or the page refreshed. But I don't know what reason causes  the increase of  values of counters when initcells() is called. .

**Comment by jfbercher** [comment]
>  It is  beautiful thing if latex_envs can support some method of loading the definitions of tex commands.

Should be feasible...

**Comment by jfbercher** [comment]
Closing this and keeping it with label "enhancement" (as it should be possible to add such functionality).
