### ISSUE TITLE
Consider suppressing equation auto-numbering in tables

### ISSUE THREAD

**Issue by NF1198** [jfbercher/jupyter_latex_envs#43]
Equation numbering produces different output in interactive mode vs. PDF output via LaTeX *when equations are embedded in tables*.

For example, upon defining the following markdown with table: 
```
\begin{equation}
y=mx + b
\end{equation}
| Col1 | Col2 | Col3 |
| --- | --- | --- |
| $$y=mx+b$$ | $$\sigma$$ | $$\alpha$$ |
```

In **interactive mode**, __four__ auto-numbered equations will be produced. However, 
in **PDF (LaTex)** output, only __one__ auto-numbered equation will be produced.

The [equation autonumbering plugin](https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/nbextensions/equation-numbering/readme.html) handles things differently: $$-$$ inline equation aren't auto-numbered where-as \begin{}\end{} tagged equations are auto-numbered.

Several possible ways to handle this: 
* Don't auto-number $$-$$ inline equations
* Expose an option to allow the user to choose whether to auto-number $$-$$ equations
* Don't auto-number any equations if the equation is within a table

**Comment by NF1198** [comment]
I found an easy solution to this: Just escape equations with single dollar signs: $..$

**Comment by jfbercher** [comment]
Too fast!
I was gonna to suggest that, and point out that \$\$ is a old TeX structure that is now deprecated in LaTeX. 

Another point is that though \$\$ . \$\$ is usually interpreted by LaTeX compilers as a displayed and numbered equation, pandoc (which essentially produces the ipynb --> TeX conversion) translates it as an inline \\( . \\) structure.
